/**
 * Master shared zones data for the UrbanCool system.
 * Reference this single file across Citizen, Planner, and Corporation Head dashboards
 * to ensure all roles inspect the exact same underlying LST coordinates and base temperatures.
 *
 * Clearly marked as mock / swappable for real backend API responses.
 */

export const masterZones = [
  {
    id: "z1",
    name: "Karve Nagar",
    lat: 18.4918,
    lng: 73.8225,
    tempC: 41.5,
    feelsLikeC: 44,
    heatLevel: "severe",
    vulnerability: "High",
    drivers: [
      "Asphalt density: 78% (SHAP: +4.1°C)",
      "Low tree canopy: 6% (SHAP: +3.0°C)",
      "No green buffers (SHAP: +1.8°C)",
    ],
    vulnerabilityScore: 94,
    details: "Elderly: 24% · Outdoor Workers: 35% · Canopy: 6%",
  },
  {
    id: "z2",
    name: "Aundh",
    lat: 18.5584,
    lng: 73.8076,
    tempC: 39.4,
    feelsLikeC: 42,
    heatLevel: "high",
    vulnerability: "High",
    drivers: [
      "High vehicle exhaust (SHAP: +2.1°C)",
      "Asphalt roads: 65% (SHAP: +2.5°C)",
      "Lack of public parks (SHAP: +1.3°C)",
    ],
    vulnerabilityScore: 82,
    details: "Elderly: 15% · Outdoor Workers: 18% · Canopy: 10%",
  },
  {
    id: "z3",
    name: "Kothrud",
    lat: 18.5074,
    lng: 73.8077,
    tempC: 38.2,
    feelsLikeC: 41,
    heatLevel: "high",
    vulnerability: "High",
    drivers: [
      "Low albedo roofing (SHAP: +3.2°C)",
      "High concrete density (SHAP: +2.8°C)",
      "Vegetation index: 0.12 (SHAP: +1.5°C)",
    ],
    vulnerabilityScore: 88,
    details: "Elderly: 18% · Outdoor Workers: 22% · Canopy: 12%",
  },
  {
    id: "z4",
    name: "Shivajinagar",
    lat: 18.5350,
    lng: 73.8250,
    tempC: 37.8,
    feelsLikeC: 40,
    heatLevel: "high",
    vulnerability: "High",
    drivers: [
      "Transit hub traffic (SHAP: +2.4°C)",
      "Concrete skyscrapers (SHAP: +2.9°C)",
      "Tree cover: 8% (SHAP: +1.8°C)",
    ],
    vulnerabilityScore: 78,
    details: "Elderly: 12% · Outdoor Workers: 28% · Canopy: 8%",
  },
  {
    id: "z5",
    name: "Warje",
    lat: 18.4857,
    lng: 73.7922,
    tempC: 36.5,
    feelsLikeC: 39,
    heatLevel: "moderate",
    vulnerability: "Medium",
    drivers: [
      "Low albedo pavement (SHAP: +1.9°C)",
      "River buffer cooling (SHAP: -1.2°C)",
      "Medium building volume (SHAP: +1.1°C)",
    ],
    vulnerabilityScore: 68,
    details: "Elderly: 10% · Outdoor Workers: 15% · Canopy: 15%",
  },
  {
    id: "z6",
    name: "Baner",
    lat: 18.5590,
    lng: 73.7868,
    tempC: 35.8,
    feelsLikeC: 38,
    heatLevel: "moderate",
    vulnerability: "Medium",
    drivers: [
      "Moderate built density (SHAP: +1.8°C)",
      "Moderate tree cover (SHAP: -0.5°C)",
      "High solar exposure (SHAP: +1.2°C)",
    ],
    vulnerabilityScore: 54,
    details: "Elderly: 8% · Outdoor Workers: 12% · Canopy: 18%",
  },
  {
    id: "z7",
    name: "Pashan",
    lat: 18.5380,
    lng: 73.7950,
    tempC: 35.1,
    feelsLikeC: 37,
    heatLevel: "moderate",
    vulnerability: "Low",
    drivers: [
      "Lake breeze cooling (SHAP: -1.8°C)",
      "Moderate tree canopy (SHAP: -0.8°C)",
      "Low residential density (SHAP: +0.5°C)",
    ],
    vulnerabilityScore: 42,
    details: "Elderly: 6% · Outdoor Workers: 10% · Canopy: 22%",
  },
  {
    id: "z8",
    name: "Bavdhan",
    lat: 18.5216,
    lng: 73.7663,
    tempC: 34.2,
    feelsLikeC: 36,
    heatLevel: "mild",
    vulnerability: "Low",
    drivers: [
      "Hilly topography wind (SHAP: -2.1°C)",
      "Good forest canopy: 40% (SHAP: -1.5°C)",
      "Paved surfaces: 22% (SHAP: +0.8°C)",
    ],
    vulnerabilityScore: 30,
    details: "Elderly: 4% · Outdoor Workers: 8% · Canopy: 40%",
  },
];
